# Generated by Django 2.0 on 2017-12-24 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('path_to_neural', models.CharField(max_length=255)),
                ('cooldown', models.DurationField()),
                ('last_request_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
    ]
