# Generated by Django 2.0 on 2017-12-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='always_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='last_request_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 3, 0)),
        ),
    ]
