# Generated by Django 2.0 on 2018-01-05 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171228_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='function_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='key',
            name='last_request_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 13, 9, 38, 641535)),
        ),
    ]
